[build]
  command = "npm run build"
  publish = "build"


[template.environment]
  ABLY_API_KEY = "rQ1shg.o-v_Rw:QsAzUjT-GI3t4a-IDsQry94Z24Yp9mOUAzrSxHdF9Qg"

  [[redirects]]
from = "/*"
to = "/index.html"
status = 200